### ISSUE TITLE
textWriter produces invalid utf8 when serializing multibyte utf16 like @

### ISSUE THREAD

**Issue by wesboyt** [amzn/ion-js#243]
'hello@' or '@' return :
Error: invalid character 0 in string
    at ParserTextRaw._read_string_helper (/Users/wesboyt/WebstormProjects/ion-js/dist/commonjs/es6/IonParserTextRaw.js:237:27)
    at ParserTextRaw._read_string2 (/Users/wesboyt/WebstormProjects/ion-js/dist/commonjs/es6/IonParserTextRaw.js:765:14)
    at ParserTextRaw._read_clob_string2 (/Users/wesboyt/WebstormProjects/ion-js/dist/commonjs/es6/IonParserTextRaw.js:859:14)
    at ParserTextRaw._run (/Users/wesboyt/WebstormProjects/ion-js/dist/commonjs/es6/IonParserTextRaw.js:1298:16)
    at ParserTextRaw.next (/Users/wesboyt/WebstormProjects/ion-js/dist/commonjs/es6/IonParserTextRaw.js:1279:18)
    at TextReader.next (/Users/wesboyt/WebstormProjects/ion-js/dist/commonjs/es6/IonTextReader.js:99:32)

Reader parses them into utf-16 just fine.

**Comment by wesboyt** [comment]
'hello@' or '@' as iontext are both working today, however instead of throwing with hello@ we return hello. I'm going to close this issue in lue of https://github.com/amzn/ion-js/issues/457 tracking that current bug status.
