### ISSUE TITLE
binary reader:  Ran out of data while reading a 1-byte unsigned int

### ISSUE THREAD

**Issue by pbcornell** [amzn/ion-js#245]
This error occurs if the caller invokes:
* binaryReader.value() twice
* binaryReader.numberValue() twice
* binaryReader.value() then binaryReader.numberValue()
* binaryReader.numberValue() then binaryReader.value()

is this the intended behavior?  seems a bit unexpected....

code to reproduce:
```javascript
let ionValue = 5;

writeln('ion: ' + ionValue);

// read as text
let reader = ion.makeReader('' + ionValue);
let textType = reader.next();
writeln('textType: ' + textType.name);
writeln('textValue: ' + reader.value());

// write as binary
let writer = ion.makeBinaryWriter();
writer.writeInt(ionValue);
writer.close();
let ionBinary = writer.getBytes();
writeln('ionBinary: ' + toHexString(ionBinary));

// read as binary
let binaryReader = ion.makeReader(ionBinary);
let binaryType = binaryReader.next();
writeln('binaryType: ' + binaryType.name);
writeln('binaryValue: ' + binaryReader.value());
writeln('binaryNumberValue: ' + binaryReader.numberValue());


export function toHexString(byteArray) {
    let sb = '';
    byteArray.forEach(b => {
        if (sb != '') { sb += ' ' }
        sb += ('0' + ((b as number) & 0xFF).toString(16)).slice(-2);
    });
    return sb;
}
export function write(s) { process.stdout.write(s) }
export function writeln(s = "") { write(s + "\n") }
```

produces:
```
ion: 5
textType: int
textValue: 5
ionBinary: e0 01 00 ea 21 05
binaryType: int
binaryValue: 5
(ノಠ益ಠ)ノ彡┻━┻
Error: Ran out of data while reading a 1-byte unsigned int.
  at Function.readUnsignedIntFrom @ ../ion-js.development/src/IonParserBinaryRaw.ts:258:18
  at ParserBinaryRaw.readUnsignedInt @ ../ion-js.development/src/IonParserBinaryRaw.ts:265:31
  at ParserBinaryRaw.load_value @ ../ion-js.development/src/IonParserBinaryRaw.ts:455:38
  at ParserBinaryRaw.numberValue @ ../ion-js.development/src/IonParserBinaryRaw.ts:596:10
  at BinaryReader.numberValue @ ../ion-js.development/src/IonBinaryReader.ts:183:24
  at Object.<anonymous> @ tests/tst.ts:89:45
  at Module._compile @ internal/modules/cjs/loader.js:701:30
  at Object.Module._extensions..js @ internal/modules/cjs/loader.js:712:10
  at Module.load @ node_modules/coffeescript/lib/coffee-script/register.js:45:36
  at tryModuleLoad @ internal/modules/cjs/loader.js:539:12
  at Function.Module._load @ internal/modules/cjs/loader.js:531:3
  at Module.require @ internal/modules/cjs/loader.js:637:17
  at require @ internal/modules/cjs/helpers.js:22:18
  at Node.loadScript @ src/lib/executors/Node.ts:238:10
  at Node._loader @ src/loaders/default.ts:10:18
  at Node.BaseExecutor._loadSuites @ src/lib/executors/Executor.ts:976:29
  at Node._loadSuites @ src/lib/executors/Node.ts:584:28
  @ src/lib/executors/Executor.ts:667:29
  @ node_modules/@theintern/common/index.js:16:7182
  at process._tickCallback @ internal/process/next_tick.js:68:7
```

**Comment by pbcornell** [comment]
Fixed by #268, closing.  Code now produces:
```
ion: 5
textType: int
textValue: 5
ionBinary: e0 01 00 ea 21 05
binaryType: int
binaryValue: 5
binaryNumberValue: 5
```
