### ISSUE TITLE
BinaryReader.timestampValue():  Seconds and precision in illegal state

### ISSUE THREAD

**Issue by pbcornell** [amzn/ion-js#247]
Related to #245 in that calling `timestampValue()` (or `value()`) twice produces this error.

Code to reproduce:
```javascript
let ionValue = new IonTimestamp(Precision.DAY, 0, 2017, 1, 1, 0, 0, 0);
writeln('ion: ' + ionValue);

// read as text
let reader = ion.makeReader('' + ionValue);
let textType = reader.next();
writeln('textType: ' + textType.name);
writeln('textValue: ' + reader.value());

// write as binary
let writer = ion.makeBinaryWriter();
writer.writeTimestamp(ionValue);
writer.close();
let ionBinary = writer.getBytes();
writeln('ionBinary: ' + toHexString(ionBinary));

// read as binary
let binaryReader = ion.makeReader(ionBinary);
let binaryType = binaryReader.next();
writeln('binaryType: ' + binaryType.name);
writeln('binaryTimestampValue: ' + binaryReader.timestampValue());
writeln('binaryTimestampValue: ' + binaryReader.timestampValue());


export function toHexString(byteArray) {
    let sb = '';
    byteArray.forEach(b => {
        if (sb != '') { sb += ' ' }
        sb += ('0' + ((b as number) & 0xFF).toString(16)).slice(-2);
    });
    return sb;
}
export function write(s) { process.stdout.write(s) }
export function writeln(s = "") { write(s + "\n") }
```

produces:
```
ion: 2017-01-01T
textType: timestamp
textValue: 2017-01-01T
ionBinary: e0 01 00 ea 65 80 0f e1 81 81
binaryType: timestamp
binaryValue: 2017-01-01T
(ノಠ益ಠ)ノ彡┻━┻
Error: Seconds and precision in illegal state.
  at new Timestamp @ ../ion-js.development/src/IonTimestamp.ts:257:64
  at ParserBinaryRaw.read_timestamp_value @ ../ion-js.development/src/IonParserBinaryRaw.ts:325:15
  at ParserBinaryRaw.load_value @ ../ion-js.development/src/IonParserBinaryRaw.ts:482:34
  at ParserBinaryRaw.timestampValue @ ../ion-js.development/src/IonParserBinaryRaw.ts:667:13
  at BinaryReader.timestampValue @ ../ion-js.development/src/IonBinaryReader.ts:199:24
  at BinaryReader.value @ ../ion-js.development/src/IonBinaryReader.ts:221:20
  at Object.<anonymous> @ tests/tst.ts:156:39
  at Module._compile @ internal/modules/cjs/loader.js:701:30
  at Object.Module._extensions..js @ internal/modules/cjs/loader.js:712:10
  at Module.load @ node_modules/coffeescript/lib/coffee-script/register.js:45:36
  at tryModuleLoad @ internal/modules/cjs/loader.js:539:12
  at Function.Module._load @ internal/modules/cjs/loader.js:531:3
  at Module.require @ internal/modules/cjs/loader.js:637:17
  at require @ internal/modules/cjs/helpers.js:22:18
  at Node.loadScript @ src/lib/executors/Node.ts:238:10
  at Node._loader @ src/loaders/default.ts:10:18
  at Node.BaseExecutor._loadSuites @ src/lib/executors/Executor.ts:976:29
  at Node._loadSuites @ src/lib/executors/Node.ts:584:28
  @ src/lib/executors/Executor.ts:667:29
  @ node_modules/@theintern/common/index.js:16:7182
  at process._tickCallback @ internal/process/next_tick.js:68:7
```

**Comment by pbcornell** [comment]
Fixed by #268, closing. Code now produces:
```
ion: 2017-01-01T
textType: timestamp
textValue: 2017-01-01T
ionBinary: e0 01 00 ea 65 80 0f e1 81 81
binaryType: timestamp
binaryTimestampValue: 2017-01-01T
binaryTimestampValue: 2017-01-01T
```
