### ISSUE TITLE
BinaryWriter:  incorrect struct L value?

### ISSUE THREAD

**Issue by pbcornell** [amzn/ion-js#249]
Generated binary for the nested struct {a: {b: {c: 5}}} looks incorrect, specifically the two `de` bytes:

```
e0 01 00 ea        // IVM
eb 81 83 d8 87 b6
81 61              // symbol 'a'
81 62              // symbol 'b'
81 63              // symbol 'c'
de                 // struct with L 'e'?
  8a de            // field 'a', struct with L 'e'?
    8b d3          // field 'b', struct with L 3
      8c 21 05     // field 'c', int 5
```

code to reproduce:
```javascript
let ionValue = '{a:{b:{c:5}}}';
writeln('ion: ' + ionValue);

// read as text
let reader = ion.makeReader(ionValue);
read(reader);

// write as binary
let writer = ion.makeBinaryWriter();
writer.writeStruct();
writer.writeFieldName('a');
writer.writeStruct();
writer.writeFieldName('b');
writer.writeStruct();
writer.writeFieldName('c');
writer.writeInt(5);
writer.endContainer();
writer.endContainer();
writer.endContainer();
writer.close();
let ionBinary = writer.getBytes();
writeln('ionBinary: ' + toHexString(ionBinary));

// read as binary
let binaryReader = ion.makeReader(ionBinary);
read(binaryReader);

function read(r) {
    let t = r.next();
    writeln('t: ' + t.name);
    r.stepIn();
    t = r.next();
    writeln('t: ' + t.name);
    r.stepIn();
    t = r.next();
    writeln('t: ' + t.name);
    r.stepIn();
    t = r.next();
    writeln('t: ' + t.name + ', v: ' + r.value());

    r.stepOut();
    r.stepOut();
    r.stepOut();
}


export function toHexString(byteArray) {
    let sb = '';
    byteArray.forEach(b => {
        if (sb != '') { sb += ' ' }
        sb += ('0' + ((b as number) & 0xFF).toString(16)).slice(-2);
    });
    return sb;
}
export function write(s) { process.stdout.write(s) }
export function writeln(s = "") { write(s + "\n") }
```

output:
```
ion: {a:{b:{c:5}}}
t: struct
t: struct
t: struct
t: int, v: 5
ionBinary: e0 01 00 ea eb 81 83 d8 87 b6 81 61 81 62 81 63 de 8a de 8b d3 8c 21 05
t: struct
t: string
(ノಠ益ಠ)ノ彡┻━┻
Error: Can't step in to a scalar value
  at BinaryReader.stepIn @ ../ion-js.development/src/IonBinaryReader.ts:115:55
  at read @ tests/tst.ts:258:6
  at Object.<anonymous> @ tests/tst.ts:250:0
  at Module._compile @ internal/modules/cjs/loader.js:701:30
  at Object.Module._extensions..js @ internal/modules/cjs/loader.js:712:10
  at Module.load @ node_modules/coffeescript/lib/coffee-script/register.js:45:36
  at tryModuleLoad @ internal/modules/cjs/loader.js:539:12
  at Function.Module._load @ internal/modules/cjs/loader.js:531:3
  at Module.require @ internal/modules/cjs/loader.js:637:17
  at require @ internal/modules/cjs/helpers.js:22:18
  at Node.loadScript @ src/lib/executors/Node.ts:238:10
  at Node._loader @ src/loaders/default.ts:10:18
  at Node.BaseExecutor._loadSuites @ src/lib/executors/Executor.ts:976:29
  at Node._loadSuites @ src/lib/executors/Node.ts:584:28
  @ src/lib/executors/Executor.ts:667:29
  @ node_modules/@theintern/common/index.js:16:7182
  at process._tickCallback @ internal/process/next_tick.js:68:7
```

**Comment by pbcornell** [comment]
Change proposed in #261 causes the repro code to produce the following, correct, output (specifically the `d7` and `d5` struct TL bytes):
```
ion: {a:{b:{c:5}}}
t: struct
t: struct
t: struct
t: int, v: 5
ionBinary: e0 01 00 ea eb 81 83 d8 87 b6 81 61 81 62 81 63 d7 8a d5 8b d3 8c 21 05
t: struct
t: struct
t: struct
t: int, v: 5
```
