### ISSUE TITLE
Decimal Test Regression in Node v12

### ISSUE THREAD

**Issue by almann** [amzn/ion-js#399]
As mentioned in #380, there is an error around decimal tests when running under Node v12:

```
× Decimal - 123d-5 (0.002s)
AssertionError: numberValue(): expected 0.00123 to equal 0.0012300000000000002
  at test  <tests/unit/IonDecimalTest.js:194:20>
  at Test.123d-5 [as test]  <tests/unit/IonDecimalTest.js:50:33>
```

The regression is likely around floating point changes in the release, so one should probably look there first.

**Comment by almann** [comment]
The test appears to be incorrect in terms of the expected value using standard approximation for IEEE-754 for base-10 representation.

```js
const buf = new ArrayBuffer(8);
const arr = new Uint8Array(buf);
const view = new DataView(buf);
const values = [0.00123, 0.0012300000000000002];

function hex(array) {
    return Array.prototype.map.call(array, x => `00${x.toString(16)}`.slice(-2)).join(' ')
}

console.log(process.version);

values.forEach(x => {
    view.setFloat64(0, x, /*littleEndian=*/ false);
    console.log(`val = ${x}`);
    console.log(`hex = ${hex(arr)}`);
});
```

Here is the run against all Node implementations:

```bash
$ for X in 8 10 12; do nvm use $X && node float.js && echo; done
Now using node v8.16.1 (npm v6.4.1)
v8.16.1
val = 0.00123
hex = 3f 54 26 fe 71 8a 86 d7
val = 0.0012300000000000002
hex = 3f 54 26 fe 71 8a 86 d8

Now using node v10.16.3 (npm v6.9.0)
v10.16.3
val = 0.00123
hex = 3f 54 26 fe 71 8a 86 d7
val = 0.0012300000000000002
hex = 3f 54 26 fe 71 8a 86 d8

Now using node v12.9.1 (npm v6.11.2)
v12.9.1
val = 0.00123
hex = 3f 54 26 fe 71 8a 86 d7
val = 0.0012300000000000002
hex = 3f 54 26 fe 71 8a 86 d8
```

**Comment by almann** [comment]
Found the issue, the rounding semantics have changed subtly between 8.x/10.x and 12.x, extended the `values` array to have the same arithmetic as `Decimal.numberValue()`.

```js
const buf = new ArrayBuffer(8);
const arr = new Uint8Array(buf);
const view = new DataView(buf);
const values = [0.00123, 0.0012300000000000002, 123 * Math.pow(10, -5)];

function hex(array) {
    return Array.prototype.map.call(array, x => `00${x.toString(16)}`.slice(-2)).join(' ')
}

console.log(process.version);

values.forEach(x => {
    view.setFloat64(0, x, /*littleEndian=*/ false);
    console.log(`val = ${x}`);
    console.log(`hex = ${hex(arr)}`);
});
```

```bash
$ for X in 8 10 12; do nvm use $X && node float.js && echo; done
Now using node v8.16.1 (npm v6.4.1)
v8.16.1
val = 0.00123
hex = 3f 54 26 fe 71 8a 86 d7
val = 0.0012300000000000002
hex = 3f 54 26 fe 71 8a 86 d8
val = 0.0012300000000000002
hex = 3f 54 26 fe 71 8a 86 d8

Now using node v10.16.3 (npm v6.9.0)
v10.16.3
val = 0.00123
hex = 3f 54 26 fe 71 8a 86 d7
val = 0.0012300000000000002
hex = 3f 54 26 fe 71 8a 86 d8
val = 0.0012300000000000002
hex = 3f 54 26 fe 71 8a 86 d8

Now using node v12.9.1 (npm v6.11.2)
v12.9.1
val = 0.00123
hex = 3f 54 26 fe 71 8a 86 d7
val = 0.0012300000000000002
hex = 3f 54 26 fe 71 8a 86 d8
val = 0.00123
hex = 3f 54 26 fe 71 8a 86 d7
```

**Comment by almann** [comment]
The root problem seems to be a difference of `Math.pow(x, y)` with respect to v8/v10 and v12.

Our `Decimal.numberValue()` implementation does `Math.pow(10, exponent)`, which is rounding differently between major versions.  The [ECMAScript standard](https://www.ecma-international.org/ecma-262/5.1/#sec-15.8.2.13) does define this as implementation specific behavior.

```js
const buf = new ArrayBuffer(8);
const arr = new Uint8Array(buf);
const view = new DataView(buf);
const values = [0.00123, 0.0012300000000000002, 123 * Math.pow(10, -5), Math.pow(10, -5)];

function hex(array) {
    return Array.prototype.map.call(array, x => `00${x.toString(16)}`.slice(-2)).join(' ')
}

console.log(process.version);

values.forEach(x => {
    view.setFloat64(0, x, /*littleEndian=*/ false);
    console.log(`val = ${x}`);
    console.log(`hex = ${hex(arr)}`);
});
```

```bash
$ for X in 8 10 12; do nvm use $X && node float.js && echo; done
Now using node v8.16.1 (npm v6.4.1)
v8.16.1
val = 0.00123
hex = 3f 54 26 fe 71 8a 86 d7
val = 0.0012300000000000002
hex = 3f 54 26 fe 71 8a 86 d8
val = 0.0012300000000000002
hex = 3f 54 26 fe 71 8a 86 d8
val = 0.00001
hex = 3e e4 f8 b5 88 e3 68 f1

Now using node v10.16.3 (npm v6.9.0)
v10.16.3
val = 0.00123
hex = 3f 54 26 fe 71 8a 86 d7
val = 0.0012300000000000002
hex = 3f 54 26 fe 71 8a 86 d8
val = 0.0012300000000000002
hex = 3f 54 26 fe 71 8a 86 d8
val = 0.00001
hex = 3e e4 f8 b5 88 e3 68 f1

Now using node v12.9.1 (npm v6.11.2)
v12.9.1
val = 0.00123
hex = 3f 54 26 fe 71 8a 86 d7
val = 0.0012300000000000002
hex = 3f 54 26 fe 71 8a 86 d8
val = 0.00123
hex = 3f 54 26 fe 71 8a 86 d7
val = 0.000009999999999999999
hex = 3e e4 f8 b5 88 e3 68 f0
```
