### ISSUE TITLE
Should fail for symbols outside of the LST 

### ISSUE THREAD

**Issue by raganhan** [amzn/ion-js#542]
See 
* https://github.com/amzn/ion-tests/blob/master/iontestdata/bad/annotationSymbolIDUnmapped.ion
* https://github.com/amzn/ion-tests/blob/master/iontestdata/bad/annotationSymbolIDUnmapped.10n
* https://github.com/amzn/ion-tests/blob/master/iontestdata/bad/fieldNameSymbolIDUnmapped.ion
* https://github.com/amzn/ion-tests/blob/master/iontestdata/bad/fieldNameSymbolIDUnmapped.10n

**Comment by wesboyt** [comment]
are you on an older version of the repo or something?
I'm getting: 
Error: SymbolID greater than maxID.
    at LocalSymbolTable.getSymbolText (/Users/wesboyt/Dev/ion-js/dist/commonjs/es6/IonLocalSymbolTable.js:60:19)
    at TextReader.annotations (/Users/wesboyt/Dev/ion-js/dist/commonjs/es6/IonTextReader.js:211:47)
    at Object.<anonymous> (/Users/wesboyt/Dev/ion-js/localTest.js:9:20)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)

**Comment by raganhan** [comment]
look at the files from the ion-tests listed in the issue. The problem happened with symbols outside of the LST that are annotated or in a struct
