### ISSUE TITLE
Zulu timestamps fails with Error: Invalid decimal 00.000Z

### ISSUE THREAD

**Issue by kadishmal** [amzn/ion-js#66]
Trying to parse `2017-05-01T01:01:00.000Z` timestamp will fail with the following error.

```
Error: Invalid decimal 00.000Z
  at Function.parse  </Users/user/ion-js/src/IonDecimal.ts:188:12>
  at Function.parse  </Users/user/ion-js/src/IonTimestamp.ts:504:28>
  at Test.suite.(anonymous function) [as test]  <tests/unit/IonTimestampTest.js:26:23>
```

**Comment by kadishmal** [comment]
It would be nice to add a "bug" label to this and other issues.
